[package]
name = "global_illumination_2d_render"
version = "0.1.0"
authors = ["Ben <benjaminkyd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
